version: 2
jobs:

  test_and_build:
    docker:
      - image: ruby:latest
    steps:
      - checkout
      - run: 
          name: Set up
          command: |
            bundle install --jobs 4
      - run:
          name: Rake :spec
          command: |
            rake 
      - run:
          name: Rake build
          command: |
            rake build
      - save_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - "/root/project/"
      - store_artifacts:
          path: /root/project


  upload:
    docker:
      - image: ruby:latest
    steps:
      - restore_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install software
          command: |
            #
      - run:
          name: Upload
          command: |
            mkdir ~/.gem
            echo "---" > ~/.gem/credentials
            echo ":rubygems_api_key: $RUBYGEMS_API_KEY" >> ~/.gem/credentials
            chmod 600 ~/.gem/credentials
            gem push pkg/*.gem
            rm ~/.gem/credentials

workflows:
  version: 2
  build_and_upload:
    jobs:
      - test_and_build
      - upload:
          requires:
            - test_and_build
          filters:
            branches:
              only:
                - main
