version: 2
jobs:

  test_and_build:
    docker:
      - image: ruby:latest
    steps:
      - checkout
      - run: 
          name: Set up
          command: |
            bundle install
      - run:
          name: Rake test
          command: |
            rake test

  upload:
    docker:
      - image: ruby:latest
    steps:
      - run:
          name: Install software
          command: |
            #apk update;
            #apk add rsync openssh sshpass;
            #echo "set ftp:passive-mode true" > ~/.lftprc
      - restore_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Upload
          command: |
            #mkdir ~/.ssh;
            #echo  "upload.bit.nl,213.136.12.217 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIVx+0N0LECcGHPywPCk9uz4/l3kNUVNe5QQRleIkMCTarkYauvRrPNPl49x3LIjF6cZsmQZX7jwgsJqEzfcF98=" > ~/.ssh/known_hosts;
            #cd /root/project/;
            #sshpass -e rsync -av .htaccess www-divd@upload.bit.nl:htdocs;
            #cd /root/project/csirt.divd.nl/_site;
            #sshpass -e rsync -av . www-divd@upload.bit.nl:htdocs/securitymeldpunt-nl;
            #cd /root/project/www.divd.nl/_site;
            #sshpass -e rsync -av . www-divd@upload.bit.nl:htdocs/divd-nl;

workflows:
  version: 2
  build_and_upload:
    jobs:
      - test_and_build
      - upload:
          requires:
            - test_and_build
          filters:
            branches:
              only:
                - main
